"""
reflection_engine.py
====================
Core data-science logic for the redesigned KRITIKOS prototype.

This module is kept separate from the interface (app.py) on purpose, so that
the machine-learning logic can be tested and understood on its own. It does two
things:

  1. trains a simple, interpretable classifier that estimates whether a cited
     source looks "academic / well-supported" or "non-academic / weak";
  2. turns that estimate into a set of lightweight reflection prompts.

Design rule (responsible AI):
  The model output is NEVER shown to the user as a verdict ("this is reliable").
  It only selects WHICH reflection cue KRITIKOS surfaces. The user keeps the
  final judgement. This protects the values of autonomy and calibrated trust.

The dataset is small and synthetic because real HU Library data was not
available (privacy + institutional constraints). Results are therefore a
proof of concept, not evidence of a production-ready system.
"""

from __future__ import annotations
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score

RANDOM_STATE = 42

FEATURES = ["text", "source_type", "domain_type",
            "peer_reviewed", "contains_citations", "uses_promotional_language"]


# ---------------------------------------------------------------------------
# 1. Synthetic dataset
# ---------------------------------------------------------------------------
def build_synthetic_dataset(n_per_class: int = 60, seed: int = RANDOM_STATE) -> pd.DataFrame:
    """Create a small, transparent synthetic dataset of source descriptions.

    label = 1 -> academic / well-supported
    label = 0 -> non-academic / weakly supported
    """
    rng = np.random.default_rng(seed)

    academic_titles = [
        "A systematic review of algorithmic bias in information retrieval",
        "Calibrated trust in automated decision systems: a longitudinal study",
        "Peer-reviewed evidence on AI literacy interventions in higher education",
        "Cognitive load and progressive disclosure in search interfaces",
        "Value sensitive design for academic recommender systems",
        "Information literacy in the age of algorithms: a meta-analysis",
    ]
    academic_snippets = [
        "This peer-reviewed study reports methodology, sample size and limitations.",
        "Results are based on a controlled experiment with 240 participants.",
        "The article was published in a Q1 journal and is widely cited.",
        "Findings are triangulated across qualitative and quantitative data.",
    ]
    nonacademic_titles = [
        "10 study hacks that will change your life with ChatGPT",
        "Why this one AI tool is the best ever (sponsored)",
        "Quick blog: my opinion on using AI for essays",
        "Top trending productivity tips you must try now",
        "Buy our premium course to ace any exam fast",
        "Unverified summary generated by a chatbot",
    ]
    nonacademic_snippets = [
        "No sources are cited and the claims are very general.",
        "The text uses promotional language and lacks evidence.",
        "This is a personal opinion posted on a blog without references.",
        "The page is an advertisement with no methodology.",
    ]

    rows = []
    for _ in range(n_per_class):
        rows.append({
            "title": rng.choice(academic_titles),
            "snippet": rng.choice(academic_snippets),
            "source_type": rng.choice(["journal_article", "conference_paper"]),
            "domain_type": rng.choice([".edu", ".org", "doi.org"]),
            "peer_reviewed": 1,
            "contains_citations": int(rng.choice([1, 1, 0])),
            "uses_promotional_language": 0,
            "label": 1,
        })
        rows.append({
            "title": rng.choice(nonacademic_titles),
            "snippet": rng.choice(nonacademic_snippets),
            "source_type": rng.choice(["blog", "social_post", "ad", "chatbot_output"]),
            "domain_type": rng.choice([".com", "medium.com", "unknown"]),
            "peer_reviewed": 0,
            "contains_citations": int(rng.choice([0, 0, 1])),
            "uses_promotional_language": int(rng.choice([1, 1, 0])),
            "label": 0,
        })
    df = pd.DataFrame(rows)
    df["text"] = df["title"] + " . " + df["snippet"]
    return df


# ---------------------------------------------------------------------------
# 2. Model
# ---------------------------------------------------------------------------
def build_model() -> Pipeline:
    """TF-IDF on text + one-hot on categoricals + numeric metadata -> LogReg."""
    preprocessor = ColumnTransformer(transformers=[
        ("text", TfidfVectorizer(stop_words="english", ngram_range=(1, 2)), "text"),
        ("cat", OneHotEncoder(handle_unknown="ignore"), ["source_type", "domain_type"]),
        ("num", "passthrough", ["peer_reviewed", "contains_citations",
                                "uses_promotional_language"]),
    ])
    return Pipeline([("pre", preprocessor),
                     ("clf", LogisticRegression(max_iter=1000))])


def train_model():
    """Train the model and return (fitted_model, metrics_dict)."""
    df = build_synthetic_dataset()
    X, y = df[FEATURES], df["label"]
    X_tr, X_te, y_tr, y_te = train_test_split(
        X, y, test_size=0.3, random_state=RANDOM_STATE, stratify=y)
    model = build_model()
    model.fit(X_tr, y_tr)
    metrics = {
        "test_accuracy": round(accuracy_score(y_te, model.predict(X_te)), 3),
        "cv_accuracy": round(cross_val_score(build_model(), X, y, cv=5).mean(), 3),
        "n_samples": len(df),
    }
    return model, metrics


# ---------------------------------------------------------------------------
# 3. From a source to reflection prompts (the design-facing part)
# ---------------------------------------------------------------------------
def classify_source(model, source: dict) -> int:
    """Return 1 (academic) or 0 (non-academic) for a single source dict."""
    row = dict(source)
    row["text"] = f"{row.get('title','')} . {row.get('snippet','')}"
    X = pd.DataFrame([row])[FEATURES]
    return int(model.predict(X)[0])


def classify_text(model, answer_text: str) -> int:
    """Classify a free-text AI answer (used by the live app).

    The model was trained on title+snippet text plus metadata. For a live AI
    answer we do not have metadata, so we infer light signals from the text
    itself (does it cite sources? does it hedge? does it sound promotional?)
    and feed a single row to the same pipeline. This keeps one model and one
    code path for both the demo and the live app.
    """
    txt = (answer_text or "").lower()
    cites = int(any(k in txt for k in [
        "study", "research", "peer-review", "journal", "et al", "(20", "according to"]))
    promo = int(any(k in txt for k in [
        "buy", "sponsored", "best ever", "amazing", "click here", "sign up"]))
    hedges = any(k in txt for k in ["may", "might", "could", "debated", "uncertain", "however"])
    row = {
        "title": answer_text[:120],
        "snippet": answer_text[120:360],
        "source_type": "journal_article" if cites else "blog",
        "domain_type": "doi.org" if cites else ".com",
        "peer_reviewed": cites,
        "contains_citations": cites,
        "uses_promotional_language": promo,
    }
    row["text"] = f"{row['title']} . {row['snippet']}"
    X = pd.DataFrame([row])[FEATURES]
    pred = int(model.predict(X)[0])
    # a hedged, non-citing answer should lean toward "weaker" prompts
    if cites == 0 and hedges:
        pred = 0
    return pred


def select_prompts(prediction: int) -> list[str]:
    """Map the internal signal to lightweight, optional reflection prompts.

    The wording is deliberately modest (an invitation, not a verdict).
    """
    if prediction == 1:   # looks academic / structured
        return ["Verify references", "Compare with literature", "Based on academic sources"]
    return ["Check the source", "This may be incomplete", "Compare with another source"]


def reflect(model, source: dict) -> dict:
    """Convenience: classify a source and return label + prompts together."""
    pred = classify_source(model, source)
    return {
        "prediction": pred,
        "label": "academic / well-supported" if pred == 1 else "non-academic / weak",
        "prompts": select_prompts(pred),
    }


# ---------------------------------------------------------------------------
# Quick self-test when run directly
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    model, metrics = train_model()
    print("Model trained.")
    print("Metrics:", metrics)

    examples = [
        {"title": "Peer-reviewed study on AI literacy interventions",
         "snippet": "Reports methodology, sample and limitations.",
         "source_type": "journal_article", "domain_type": "doi.org",
         "peer_reviewed": 1, "contains_citations": 1, "uses_promotional_language": 0},
        {"title": "10 AI hacks to finish your essay fast (sponsored)",
         "snippet": "No sources cited, promotional language.",
         "source_type": "ad", "domain_type": ".com",
         "peer_reviewed": 0, "contains_citations": 0, "uses_promotional_language": 1},
    ]
    for ex in examples:
        out = reflect(model, ex)
        print(f"\n{ex['title']}")
        print(f"  -> {out['label']}")
        print(f"  -> prompts: {out['prompts']}")
